fn source_record(
    operation: crowsi_credential_authority_contracts::ManagementOperationV2,
    prepared: &EndpointPreparedOperationV2,
    verified: &VerifiedManagementIdentity<'_>,
    authority_config_generation: u64,
    uv: &SignedAuthorityExchangeV1,
    grant_action: Option<String>,
    revocation_saga: Option<crate::management_v2_record::RevocationSagaV2>,
) -> ManagementRecordV2 {
    ManagementRecordV2 {
        operation,
        prepared: prepared.clone(),
        owner_ref: verified.owner.opaque_owner_ref.clone(),
        service_id: verified.identity.assertion.service_id.clone(),
        pairwise_subject: verified.identity.assertion.pairwise_subject.clone(),
        authority_config_generation,
        source_identity_exchange: verified.identity_exchange.clone(),
        source_options_exchange: uv.clone(),
        actor_options_identity_exchange: None,
        actor_options_exchange: None,
        source_finish_uv_exchange: None,
        source_approval_identity_exchange: None,
        source_approval_acceptance_sha256: None,
        target_finish_uv_exchange: None,
        independent_finish_uv_exchange: None,
        target_identity_exchange: None,
        independent_identity_exchange: None,
        target_proof: None,
        approved_by_device_ref: None,
        provider_transfer_id: None,
        grant_action,
        source_revocation_ceremony: None,
        revocation_finalization: None,
        independent_revocation_finalization: None,
        independent_revocation_ceremony: None,
        transfer_context: None,
        transfer_provider_acceptance: None,
        transfer_provider_history: Vec::new(),
        transfer_provider_history_count: 0,
        transfer_provider_history_digest_sha256:
            crate::management_v2_provider_progress::empty_digest("transfer"),
        revocation_saga,
    }
}
